version: "3.9"

services:

  bse:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: chandra
      MYSQL_DATABASE: bsefastapi
      MYSQL_USER: cncdragneel
      MYSQL_PASSWORD: chandra@123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
