version: "3.9"

services:

  bsedb:
    container_name: bsedb
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - bsefastapinetwork
  
  bsepgadmin:
    container_name: bsepgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - bsedb
    networks:
      - bsefastapinetwork
  
  bse:
    container_name: bse
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c  "alembic upgrade head &&
              uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - bsedb
      - bsepgadmin
    networks:
      - bsefastapinetwork

networks:
  bsefastapinetwork:
    driver: bridge