version: "3.9"

services:

  bsedb:
    container_name: bsedb
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bsedeals
    networks:
      - bsefastapinetwork
  
  bsepgadmin:
    container_name: bsepgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80
    depends_on:
      - bsedb
    networks:
      - bsefastapinetwork
  
  bse:
    container_name: bse
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c  "alembic upgrade head &&
              uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - bsedb
      - bsepgadmin
      - redis
      - flower
    networks:
      - bsefastapinetwork
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - bsefastapinetwork
  
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - bse
      - redis
    networks:
      - bsefastapinetwork

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A celery_worker.celery_app beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - bse
      - redis
      - celery_worker
    networks:
      - bsefastapinetwork

  flower:
    container_name: flower
    build: .
    command: celery -A celery_worker.celery_app --broker=redis://redis:6379/0 flower --basic_auth=admin:admin
    ports:
      - 5555:5555
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - bsefastapinetwork

networks:
  bsefastapinetwork:
    driver: bridge