"""dealsmigration

Revision ID: 9c7f887baf5d
Revises: 
Create Date: 2023-06-24 11:17:10.377089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7f887baf5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_date', sa.String(length=30), nullable=True),
    sa.Column('security_code', sa.String(length=30), nullable=True),
    sa.Column('security_name', sa.String(length=100), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('deal_type', sa.String(length=5), nullable=True),
    sa.Column('quantity', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deals')
    # ### end Alembic commands ###
